### ISSUE TITLE
Issue with an exception

### ISSUE THREAD

**Issue by pezsgo12** [Kaedrin/warhammer-mod-manager#24]
Hi,

I encountered an issue with an exception being thrown, here are the details.
I added the game as an external game to steam. Then added my mods in the steam site.
After it, I downloaded the mod manager, and launched it. It didn't see the game at first, but I have written the exepath into the GameData.xml. After a new launch, the following message occurred: 
![image](https://user-images.githubusercontent.com/24295313/50372083-0a8b2500-05c8-11e9-8645-089204ae90f5.png)
(It is mostly in hungarian)
It basically says, some "length" param is less than zero.

Any ideas?
Thanks in advance!

**Comment by Awrel** [comment]
Yea i also got this problem

**Comment by Kaedrin** [comment]
You must own the game via Steam for this manager to work.
