### ISSUE TITLE
Steam must be running

### ISSUE THREAD

**Issue by Meiun** [Kaedrin/warhammer-mod-manager#28]
I play through wine and or proton and the mod manager cannot see either wine steam or native Linux steam.

Unfortunate since the only part of the game that doesn't work is the launcher and enabling mods is impossible.

The native Linux version of the game is awful. No mod support at all and no crossplay. Can crossplay with windows friends in vanilla, just can't activate mods.

Being able to point to steam would be good.

**Comment by Kaedrin** [comment]
Steamworks has a Linux version but I'm using .Net proper and not .Net Core so the entire tool isn't usable on Linux. In the future when the full XAML space gets moved into the .Net Core library I'll be able to make 2.0 available to Linux but not until then.
