### ISSUE TITLE
Not seeing new factions when using launcher.

### ISSUE THREAD

**Issue by Stevendh** [Kaedrin/warhammer-mod-manager#31]
I'm not able to see the new factions added in latest DLC when using this launcher.

**Comment by Kaedrin** [comment]
Are you using family sharing?

**Comment by Ylech** [comment]
I am having the same issue, i am not family sharing. My game is installed in a different library from my main steam folder.

**Comment by Ylech** [comment]
Doesn't matter, it's not your launcher to blame but other mod, mea culpa. In my case it was "Main Campaign Capital Fix" and it is a known issue right now. Sorry for the inconvenience.
