### ISSUE TITLE
Problems with Warhammer I

### ISSUE THREAD

**Issue by rgilsoul** [Kaedrin/warhammer-mod-manager#4]
If I am reading correctly, I should be able to use this manager with Warhammer I as well as II.  Both of my games are on my H drive instead of C.  I cannot seem to figure out how to get it to find my copy of Warhammer I.

**Comment by AlJoelson** [comment]
It seemed to be supported in v1.1 but that support was then removed in v1.1a.

You'll have to wait until v1.3, I suppose, for Kaedrin to reinstate that support.

**Comment by Kaedrin** [comment]
Warhammer I won't be supported until version 2.0
