### ISSUE TITLE
[Solved] Program worked perfectly, but now it crashes instantly without even showing a window

### ISSUE THREAD

**Issue by JimmySlickD** [Kaedrin/warhammer-mod-manager#5]
Hi,
This mod manager is just awesome, I've used it for a while now, but out of nowhere it stopped working. Instead it'll only show up in the list of processes for a few seconds, at most, before disappearing again. 
This started just after downloading a few more mods.
Now I've tried to delete all mods.
Tried using the 3 latest versions, all with same result.
Tried deleting the manager and game files, reinstalling it, with same results. 
Any ideas?

**Comment by JimmySlickD** [comment]
it seems to be an ArgumentNullException that isn't handled properly and shuts the application down. Guessing the way the application saves data has corrupted some value and since I can't find its location, i have no way of fixing it. 
Btw. since I can't use the app's Revert to Vanilla option, I can't run mods at all. Be warned; if you use this tool, it might require a reinstall of windows to fix/revert at this point.

**Comment by JimmySlickD** [comment]
Aha, deleting `mod_manager_settings.txt`, under `(...)\AppData\Roaming\The Creative Assembly\scripts` fixed it. 

Kaedrin, if you upload the source code, this bug would be so easy to fix...

**Comment by Kaedrin** [comment]
Try the 1.4 beta

**Comment by Kaedrin** [comment]
v1.4 fixes how the pathing is handled.
