### ISSUE TITLE
Comunity framework

### ISSUE THREAD

**Issue by NJSFC** [Kaedrin/warhammer-mod-manager#8]
Hi nice program
But i have a issue
The 'Comunity framework' mod is never listed in you program
some other mods need this mod , and i cant enable it 

is this normal ?

**Comment by NJSFC** [comment]
Thanks for the response

Yes

What should i do ?

**Comment by Kaedrin** [comment]
It's working for me and it's called zzzzz_scripting_framework.pack
Are you sure that's not showing up?

**Comment by NJSFC** [comment]
Yes im sure.

If i use the standard mod manager in the game launcher , it shows up and
all works well. ( but is a pain in the ... as you know)

if i use your launcher it dont show up (so i cant select it) and the mods
depending on the ' zzzzz_scripting_framework.pack ', dont work well.

So for is the only problem i have with your launcher, all other mods show
and i cant select or unselect them.

Your launcher is so mutch better , i hope you can figure this out.

**Comment by Kaedrin** [comment]
It's working for me and the author. Try unsubscribing and resubscribing on steam so that it forces a download. Then run my manager again so that it can push the .pack file to data.
